

---
title: 'Reproducible Research: Peer Assessment 1'
output:
  word_document: default
  pdf_document: default
  html_document:
    keep_md: yes
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Loading R Packages

```{R}

library(plyr)
library(chron)
require(ggplot2)
require(scales)
library(ggplot2)
 
```


## Loading and preprocessing the data
*Assume the data file of activity.csv has been saved in a proper directory.*
```{R}
d=read.csv(file="C:/Temp/repdata_data_activity/activity.csv",sep= ",", h=T)

```
## What is mean total number of steps taken per day?
####    1.1. Calculate the total number of steps taken per day

```{R }
#d
#summary(d)
#nrow(d)

#d1 <- aggregate(d[, 1], list(d$date), sum)


d_1 <- ddply(d, ~date, summarise, total_steps_per_day=sum (steps) , rm.na = TRUE )
d_1
 
```

####1.2. Histogram of the total number of steps taken each day
```{R}
jpeg("C:/Temp/repdata_data_activity/figures/histogram_steps_per_day.jpeg");
ggplot(d_1, aes(x = total_steps_per_day)) +
  geom_histogram(col="black", fill = "dark blue", binwidth = 1000) +
  labs(title = "Histogram of steps per day", x = "Steps per day", y = "Frequency")

dev.off()
```

####1.3 The mean and median of the total number of steps taken per day
```{R}
d_2 <- ddply(d, ~date, summarise, mean_steps=mean(steps), median_steps= median(steps) , rm.na = TRUE )

d_2
#mean (d1$x, na.rm = TRUE )
#median (d1$x, na.rm = TRUE )
```

## What is the average daily activity pattern?

####2.1. Make a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis) 


```{R  include=FALSE }
str(d)
d$interval <- factor(d$interval)
d_nona <- subset(d, !is.na(d$steps))
d_3 <- ddply(d_nona, ~ interval ,summarise, mean_steps=mean(steps), rm.na = TRUE)
str(d_3)
d_3$interval <- as.numeric(as.character(d_3$interval))
str(d_3)
```

```{R}

jpeg("C:/Temp/repdata_data_activity/figures/Time series plot.jpeg");
ggplot(data=d_3, aes(x= interval, y=mean_steps, group =1)) + geom_line(color= "dark blue")

dev.off()
```


####2.2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

```{R}
d_3$mx <- max(d_3$mean_steps, na.rm= true)

newdata <- unique( subset (d_3, d_3$mean_steps == d_3$mx) )
newdata

```
At the inverval of **835** contains the maximum number of steps.

## Imputing missing values

####3.1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)  

```{R}

n <- sum(is.na(d$steps) | is.na(d$date) | is.na(d$interval))
n


```
 
There are `r n` missing values in the dataset


####3.2. filling in all of the missing values in the dataset, replace missing value with mean steps of the day
#### &
####3.3. Create a new dataset that is equal to the original dataset but with the missing data filled in.

```{R}
#n1 <- sum(is.na(d$steps))
#n1
rplc<- merge (d, d_2, by = "date")
rplc$steps[is.na(rplc$steps)] <- rplc$mean_steps
n2<-sum(is.na(rplc$steps))
n2
```
The missing data is replaced with the means steps of the day. 
The dataset with missing data filled in is created. Now there are only `r n2` missing data points, used to be `r n` missing data points.



####3.4. Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

```{R}

rplc1 <- ddply(rplc, ~date, summarise, total_steps=sum(steps))

as.numeric(rplc1$total_steps)


jpeg("C:/Temp/repdata_data_activity/figures/Histogram_w_imputing_missing.jpeg");
ggplot(rplc1 , aes(x = total_steps)) +
  geom_histogram(col="black", fill = "dark blue", binwidth = 1000) +
  labs(title = "Histogram of steps per day", x = "Steps per day", y = "Frequency")
dev.off()

```

```{R, include= FALSE}

rplc1 <- ddply(rplc, ~date, summarise, mean_steps_day=mean(steps), median_steps_day= median(steps))
n_r<-sum(is.na(rplc1$mean_steps_day) | is.na(rplc1$median_steps_day) )
n_r
d1 <- ddply(d, ~date, summarise, mean_steps_day=mean(steps), median_steps_day= median(steps))
n_d1<-sum(is.na(d1$mean_steps_day) | is.na(d1$median_steps_day) )
n_d1

```
The dataset filled with mean value now constains only `r n_r`  missing data points, while the original data contains `r n_d1`.


## Are there differences in activity patterns between weekdays and weekends?

#### 4.1 Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.

```{R}

#library(chron)

rplc$wk = ifelse (chron::is.weekend(rplc$date), "weekend", "weekday")

```
#### 4.2. A panel plot containing a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).

```{R, include= FALSE}
 
rplc_nona <- subset(rplc, !is.na(d$steps))

rplc_nona <- ddply(rplc_nona , .(wk, interval), summarise, mean_s_w_I=mean(steps))

str(rplc_nona)
as.numeric(rplc_nona$interval)

```
The following graph shows the activity pattern for the weekdays and weekend. Comparing with the weekend, people tend to be more active in the early time of a day; while people have about the same level of activity in the later time (late afternoon and evening) as in the morning of a day. 

```{R}

jpeg("C:/Temp/repdata_data_activity/figures/Time_series_Weekday_weekend.jpeg");

ggplot(rplc_nona, aes(x= interval,y=mean_s_w_I, color = wk, group=1)) +geom_line() +
        facet_grid(factor(wk) ~ .) +
    xlab("Interval") +
    ylab( "Steps") +
    theme(axis.title.y = element_text(face='bold',size=14,color='black', vjust=1),
          axis.text.x = element_text(face='bold',size=14,color='black'),
          legend.title=element_blank())

dev.off()



```
